language: java
scala: 2.12.6
os: linux
jdk: oraclejdk8

addons:
  apt:
    packages:
    - rpm
    - fakeroot

sudo: false
cache:
  apt: true
  directories:
  - $HOME/.sbt
  - $HOME/.m2
  - $HOME/.ivy2

env:
  global:
  - secure: bK5zEd2s3y+ScGwuGcxlP0tXx83nvurmF/SWuQSmI0A2KRelipGSSY2BTa+URKk9smJusJIZUi72EqEwMHDhxLCfHomjze5BmpJB5Mr3fQI700nxPEA95cbM4Z1G9+K6fYWy2pi5S7Xmz1Sg07bP4sfzyVYlNB20aquLCmB9Llk=
  - secure: iY6MLAx39wW8y4uPZxt86FiNkLdrVHaAKCIcp7P35c0Zi1T0aaPTVTwZMS1uJAYs7e3Nh7gv7yU0hZR6t3klYPNjQdS7LHTgITIejBmikkBTkVqfpIYEOyrfDSaT59YlGrBiidegEGnw84kD4dFDmjnUY0ViCwOpJKr0a0Iokls=

before_install:
  # travis sets the java options which breaks tests that check the applied memory settings
  - unset _JAVA_OPTIONS
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
      brew install xz;
      brew install sbt;
    fi

before_script:
- curl -L --create-dirs -o $HOME/.sbt/launchers/1.1.6/sbt-launch.jar http://dl.bintray.com/sbt/maven-releases/org/scala-sbt/sbt-launch/1.1.6/sbt-launch.jar

# job definitions

jobs:
  include:
    - stage: validate
      script: sbt "^validate"

    - stage: scripted
      script: sbt "^validateUniversal"
      name: "scripted universal tests"
    - script: sbt "^validateJar"
      name: "scripted jar tests"
    - script: sbt "^validateBash"
      name: "scripted bash tests"
    - script: sbt "^validateAsh"
      name: "scripted ash tests"
    - script: sbt "^validateRpm"
      name: "scripted rpm tests"
    - script: sbt "^validateDebian"
      name: "scripted debian tests"
    - script: sbt "^validateDockerUnit"
      name: "scripted docker unit-tests"
    - script: sbt "^validateJdkPackagerTravis"
      name: "scripted jdk-packager tests"
      # docker configuration as described in
      # https://docs.travis-ci.com/user/docker/
    - script: sbt "^validateDocker"
      name: "scripted docker integration-tests"
      services: docker
      sudo: required
    - script: sbt "^validateOSX"
      os: osx
      osx_image: xcode8

    - stage: release
      script:
        - gpg --import project/.gnupg/key.asc
        - gem install github_changelog_generator
        - sbt "^release"