language: java
scala: 2.12.6
os: linux
jdk: oraclejdk8

addons:
  apt:
    packages:
    - rpm
    - fakeroot

sudo: false
cache:
  apt: true
  directories:
  - $HOME/.sbt
  - $HOME/.m2
  - $HOME/.ivy2

env:
  global:
  - secure: bK5zEd2s3y+ScGwuGcxlP0tXx83nvurmF/SWuQSmI0A2KRelipGSSY2BTa+URKk9smJusJIZUi72EqEwMHDhxLCfHomjze5BmpJB5Mr3fQI700nxPEA95cbM4Z1G9+K6fYWy2pi5S7Xmz1Sg07bP4sfzyVYlNB20aquLCmB9Llk=
  - secure: iY6MLAx39wW8y4uPZxt86FiNkLdrVHaAKCIcp7P35c0Zi1T0aaPTVTwZMS1uJAYs7e3Nh7gv7yU0hZR6t3klYPNjQdS7LHTgITIejBmikkBTkVqfpIYEOyrfDSaT59YlGrBiidegEGnw84kD4dFDmjnUY0ViCwOpJKr0a0Iokls=

before_install:
  # travis sets the java options which breaks tests that check the applied memory settings
  - unset _JAVA_OPTIONS
  - if [[ "$TRAVIS_OS_NAME" = "osx" ]]; then
      brew update;
      brew install xz;
      brew install sbt;
    fi

before_script:
- curl -L --create-dirs -o $HOME/.sbt/launchers/1.1.6/sbt-launch.jar http://dl.bintray.com/sbt/maven-releases/org/scala-sbt/sbt-launch/1.1.6/sbt-launch.jar

# job definitions

jobs:
  include:
    - stage: validate
      script: sbt "^validate"
    - stage: scripted
      script: sbt "^validateUniversal"
      name: "scripted universal tests"
    - script: sbt "^validateJar"
      name: "scripted jar tests"
    - stage: release
      script: "echo releasing"